$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $root

$python = Join-Path $root ".venv\Scripts\python.exe"
if (-not (Test-Path $python)) {
  throw "Missing venv python at $python. Create venv first (see README)."
}

# Ensure PyInstaller is available
& $python -m pip show pyinstaller *> $null
if ($LASTEXITCODE -ne 0) {
  & $python -m pip install --upgrade pyinstaller
}

# Clean prior outputs
if (Test-Path "$root\dist") { Remove-Item -Recurse -Force "$root\dist" }
if (Test-Path "$root\build") { Remove-Item -Recurse -Force "$root\build" }

$icon = Join-Path $root "resources\icon.ico"
if (-not (Test-Path $icon)) {
  throw "Missing icon at $icon"
}

# Windows add-data separator is ';'
$addData = "resources;resources"

# Generate build info for the app (used in the main window title).
# Build number format: yyMMddHHmm (e.g. 2512140956)
$buildPy = Join-Path $root "src\sgm\_build.py"

$buildNum = (Get-Date).ToString("yyMMddHHmm")
$gitSha = $null

try {
  $gitSha = (git rev-parse --short HEAD 2>$null).Trim()
  if ([string]::IsNullOrWhiteSpace($gitSha)) { $gitSha = $null }
} catch {
  $gitSha = $null
}

$generated = @(
  "# Auto-generated by build_exe.ps1"
  "BUILD = '$buildNum'"
  "GIT_SHA = '$gitSha'"
)

Set-Content -Path $buildPy -Value $generated -Encoding UTF8

& $python -m PyInstaller `
  --noconfirm `
  --clean `
  --onefile `
  --windowed `
  --name "SprintGameManager" `
  --icon "$icon" `
  --paths "src" `
  --add-data "$addData" `
  "main.py"

Write-Host "Built: $root\dist\SprintGameManager.exe"
